[package]
name = "core"
version = "0.1.0"
edition = "2018"


[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
bytes = "1.1.0"
tokio-util = { version = "0.6.8", features = ["codec"] }
snafu = { version = "0.6.10", features = ["backtraces"]}
log = "0.4.14"