[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
core = { path = "../core" }
clap = "3.0.0-beta.4"
tokio = { version = "1.11.0", features = ["full"] }
tokio-util = { version = "0.6.8", features = ["full"] }
futures = "0.3.17"
env_logger = "0.9.0"
log = "0.4.14"